AWSTemplateFormatVersion: '2010-09-09'
Description: >-
   Template to create the Lambda that is going to interact 
   with the ES cluster.
   **WARNING** You will be billed for the AWS resources used if you create a stack
   from this template.

Parameters:
  lambdaArn:
    Description: The ARN of the lambda function
    Type: String 

Resources:
    ApiGatewayRestApi:
        Type: "AWS::ApiGateway::RestApi"
        Properties:
            Name: "search-es-api"
            Description: "Public API for searching an Amazon Elasticsearch Service domain"
            ApiKeySourceType: "HEADER"
            EndpointConfiguration: 
                Types: 
                  - "REGIONAL"

    ApiGatewayMethod:
        Type: "AWS::ApiGateway::Method"
        Properties:
            RestApiId: !Ref ApiGatewayRestApi
            ResourceId: !GetAtt
            - ApiGatewayRestApi
            - RootResourceId
            HttpMethod: "GET"
            AuthorizationType: "NONE"
            ApiKeyRequired: false
            RequestParameters: 
                "method.request.querystring.q": true
            MethodResponses: 
              - 
                ResponseModels: 
                    "application/json": "Empty"
                StatusCode: "200"
            Integration: 
                ContentHandling: "CONVERT_TO_TEXT"
                IntegrationHttpMethod: "POST"
                IntegrationResponses: 
                  - 
                    ResponseTemplates: {}
                    StatusCode: "200"
                PassthroughBehavior: "WHEN_NO_MATCH"
                TimeoutInMillis: 29000
                Type: "AWS_PROXY"
                Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"           

    ApiGatewayStage:
        Type: "AWS::ApiGateway::Stage"
        DependsOn: 
        - ApiGatewayRestApi
        Properties:
            StageName: "search-es-api-test"
            DeploymentId: !Ref ApiGatewayDeployment
            RestApiId: !Ref ApiGatewayRestApi
            CacheClusterEnabled: false
            CacheClusterSize: "0.5"
            MethodSettings: 
              - ResourcePath: !Join ['',['/',!Ref ApiGatewayRestApi]]
                HttpMethod: GET
                MetricsEnabled: false
                ThrottlingBurstLimit: 500
                ThrottlingRateLimit: 1000
            TracingEnabled: false

    ApiGatewayDeployment:
        Type: "AWS::ApiGateway::Deployment"
        DependsOn: 
        - ApiGatewayMethod
        Properties:
            RestApiId: !Ref ApiGatewayRestApi

    S3Paramater:
        Type: AWS::SSM::Parameter
        DependsOn: 
        - ApiGatewayDeployment
        Properties:
            Name: apiUrl
            Type: String
            Value: !Join ['',['https://',!Ref ApiGatewayRestApi, '.execute-api.',!Ref AWS::Region,'.amazonaws.com/',!Ref ApiGatewayStage]]
            Description: SSM Parameter of S3 bucket.        

Outputs: 
  ApiGatewayRestApi:
    Value: !Ref ApiGatewayRestApi
  ApiGatewayDeployment:
    Value: !Ref ApiGatewayDeployment
  ApiGatewayStage:
    Value: !Ref ApiGatewayStage
